# Generated by Django 3.0.4 on 2024-08-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerstudy', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='Image',
            index=models.Index(fields=['image_name'], name='idx_image_name'),
        ),

        migrations.AddIndex(
            model_name='DockerHubUser',
            index=models.Index(fields=['username'], name='idx_username'),
        ),
    ]
