# Generated by Django 5.1 on 2024-08-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerstudy', '0002_add_image_name_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrypeScanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_timestamp', models.DateTimeField()),
                ('container_image', models.CharField(max_length=255)),
                ('os_name', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('vulnerability_id', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('package_name', models.CharField(max_length=255)),
                ('package_version', models.CharField(max_length=100)),
                ('fix_state', models.CharField(max_length=50)),
                ('fix_versions', models.JSONField(default=list)),
                ('cve_ids', models.JSONField(default=list)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='dockerhubuser',
            name='idx_username',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='idx_image_name',
        ),
        migrations.AlterField(
            model_name='commit',
            name='changed_files',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='commit',
            name='parents',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='image',
            name='builds',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='image',
            name='pagination',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='image',
            name='response',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='repository',
            name='branches',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='repository',
            name='commits',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='repository',
            name='languages',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='repository',
            name='releases',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='repository',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='grypescanresult',
            index=models.Index(fields=['container_image'], name='dockerstudy_contain_3f26e2_idx'),
        ),
        migrations.AddIndex(
            model_name='grypescanresult',
            index=models.Index(fields=['vulnerability_id'], name='dockerstudy_vulnera_484efa_idx'),
        ),
        migrations.AddIndex(
            model_name='grypescanresult',
            index=models.Index(fields=['severity'], name='dockerstudy_severit_bb83e4_idx'),
        ),
        migrations.AddIndex(
            model_name='grypescanresult',
            index=models.Index(fields=['package_name'], name='dockerstudy_package_4f47d9_idx'),
        ),
        migrations.AddIndex(
            model_name='grypescanresult',
            index=models.Index(fields=['scan_timestamp'], name='dockerstudy_scan_ti_5c8cb6_idx'),
        ),
    ]
